jenkins-x/terraform-aws-eks-jx

- README.md
- jenkins-x/irsa.tf
- jenkins-x/jx-requirements.yml.tpl
- jenkins-x/local.tf
- jenkins-x/main.tf
- jenkins-x/outputs.tf
- jenkins-x/variables.tf
- main.tf
- outputs.tf
- variables.tf
- vault/main.tf
- vault/outputs.tf
- vault/variables.tf
> feat: initial code push

- scripts/aws-asume-role.sh
- the script will also expect MFA auth details
fixes #9
> fix: adding a helper script for assuming an AWS role

- main.tf
> fix: Generate jx-requirements.yml in current working directory

- Makefile
- README.md
- examples/backend/main.tf
- examples/backend/outputs.tf
- examples/basic/main.tf
- examples/basic/variables.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/outputs.tf
- outputs.tf
- scripts/release.sh
- variables.tf
- updating README
- adding section about state management
- adding example for state management
- aligning cluster configuration variables with the ones used in GKE module
- removing unused wait_for_cluster_cmd and manage_aws_auth variables
> feat: adding ability to create Vault IAM user

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> fix: expose cluster version variable

- modules/vault/main.tf
> fix: add explicit dependence on resource creation when querying data source

- main.tf
- modules/cluster/outputs.tf
- modules/vault/outputs.tf
- outputs.tf
> fix: invalid index error

- README.md
- main.tf
- modules/cluster/storage.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
> fix: delete non-empty s3 buckets created by the module

- README.md
> docs: add wget to the list of pre-reqs

- README.md
> docs: fix location in README to add IAM Roles for Service Accounts

- main.tf
> fix: check for empty tuple when accessing s3 bucket information

- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- modules/dns/main.tf
- modules/vault/main.tf
- modules/vault/variables.tf
The changes in this PR, apart from version changes, are the result of running `terraform fmt` 
fixes #81
> chore: update external module versions

- README.md
> docs: fix broken link in readme for configuring vault for eks

- .github/issue_template.md
- .github/pull_request_template.md
- .gitignore
- Makefile
- README.md
- jenkins-x.yml
- modules/vault/main.tf
- modules/vault/variables.tf
- scripts/ci.sh
- variables.tf
Also add issue and PR template
fixes #70 and #72
> feat: add tfsec and validate to build-pr check

- .gitignore
- Makefile
- jenkins-x.yml
- local.tf
- main.tf
- modules/jx-requirements.yml.tpl
- modules/vault/main.tf
- modules/vault/outputs.tf
- modules/vault/variables.tf
- scripts/ci.sh
- spec/test_spec.sh
- variables.tf
- if vault_url is specified Vault module resources are not generated
- the resulting requirements file contains the Vault URL, but needs ti be edited with remaining external Vault configuration before running Boot
fixes #95
> feat: allow to pass vault_url variable to indicate external Vault setup

- examples/dev-team/main.tf
- examples/dev-team/outputs.tf
- jenkins-x.yml
- modules/cluster/main.tf
- modules/cluster/variables.tf
This PR fixes the issue with broken PR checks:
```
Error: No valid credential sources found for AWS Provider.
Please see https://terraform.io/docs/providers/aws/index.html for more information on
providing credentials for the AWS Provider
on main.tf line 12, in provider "aws":
12: provider "aws" {
```
fixes #116
> chore: change aws creds mount path

- Makefile
- examples/backend/main.tf
- examples/basic/main.tf
- modules/cluster/irsa.tf
- modules/cluster/outputs.tf
- modules/dns/outputs.tf
- modules/dns/variables.tf
- modules/vault/local.tf
This PR fixes the issues with no formatting for the sub-directories
Also ran `terarform fmt -recursive`, so some of the files which were not formatted before, have been formatted.
fixes #118
> fix: add recursive flag to terraform fmt

- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/output.tf
- modules/backup/variables.tf
- modules/jx-requirements.yml.tpl
- outputs.tf
- variables.tf
Create required resources for Velero when `enable_backup` is `true`.
```
module "eks-jx" {
source  = "jenkins-x/eks-jx/aws"
enable_backup = true
}
```
fixes #17
> feat(backup): velero storage and IAM

- README.md
- modules/cluster/variables.tf
- variables.tf
> fix: make key_name optional

- README.md
- examples/dev-team/main.tf
- examples/nat/main.tf
- examples/s3-kms/main.tf
- examples/s3-kms/outputs.tf
- examples/s3-kms/variables.tf
- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/cluster/storage.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
> feat: encrypt s3 buckets by default

- modules/cluster/irsa.tf
- modules/cluster/outputs.tf
- outputs.tf
- spec/test_spec.sh
> refactor: remove jx ui service account creation

- modules/cluster/irsa.tf
> fix: empty tuple when setting jx2 boolean variable to false

- README.md
- local.tf
- templates/jx-requirements.yml.tpl
- variables.tf
> fix: set ignoreLoadBalancer to false by default

- modules/cluster/irsa.tf
> fix: check for existence of namespace to avoid error after a destroy

- modules/cluster/main.tf
> feat: add a secret to store service account annotations

- modules/cluster/main.tf
> fix: fix name for the controllerbuild service account

- README.md
- examples/cluster-access/main.tf
- examples/cluster-access/outputs.tf
- examples/cluster-access/variables.tf
- examples/jx3/main.tf
- examples/jx3/outputs.tf
- examples/jx3/variables.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> feat: expose cluster access variables

- README.md
- examples/worker-group-launch-templates/main.tf
- examples/worker-group-launch-templates/outputs.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
This sorta closes #131 - the original plan was to expose it directly, but it gets complicated and there are nuances around autoscaling so I figure this is what most people want although opinionated.
Perhaps a second PR could allow providing a completely custom launch template if someone needs that
> feat: Create Launch Templates for each AZ - fixes #131

- modules/cluster/irsa.tf
> fix: add AssumeRoleWithWebIdentity to tekton bot policy

- modules/cluster/irsa.tf
> fix: create iam role for tekton sa in jx3

- modules/cluster/irsa.tf
> fix: modify tekton sa role name

- modules/cluster/main.tf
> fix: add ECR poweruser policy to nodegroup iam

- README.md
- local.tf
- main.tf
- templates/jx-requirements.yml.tpl
- variables.tf
> feat: add registry to requirements configmap

- README.md
- modules/cluster/variables.tf
- variables.tf
> fix: change root volume size for self managed nodes to 50GB

- README.md
- variables.tf
> chore: update k8s version to 1.17

- README.md
- local.tf
- main.tf
- modules/cluster/charts.tf
- modules/cluster/irsa.tf
- modules/cluster/local.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- templates/jx-requirements.yml.tpl
- variables.tf
This also adds the git-operator related variables - git_url, username and bot-token
Will rebase and add tests after #129 is merged.
fixes #181 
fixes #174
> feat: automatically install the jx git operator

- modules/cluster/main.tf
> fix: do not provision worker group launch templates for eks managed node group

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> feat: expose variables to control cluster and vpc creation

- README.md
- examples/existing-cluster/main.tf
- examples/existing-cluster/outputs.tf
- examples/existing-cluster/variables.tf
> feat: install jx components in existing EKS cluster

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
> fix: pass region to eks update-config

- examples/jx3/main.tf
- jenkins-x.yml
- main.tf
- modules/health/main.tf
- modules/health/variables.tf
- variables.tf
> feat: install kuberhealthy components

- README.md
- examples/asm/main.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> feat: add option to encrypt ebs volumes for self managed worker nodes

- modules/cluster/charts.tf
> fix: use set_sensitive instead of set for bot token

- README.md
- examples/envelope-encryption/main.tf
- examples/envelope-encryption/outputs.tf
- examples/envelope-encryption/variables.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> feat: add envelope encryption for k8s secrets

- README.md
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/cluster/irsa.tf
- modules/cluster/variables.tf
- variables.tf
Add flags to control iam role creations, making it easier to integrate with existing clusters
fixes #200
> feat: add flags to control iam role creation for existing clusters

- modules/cluster/irsa.tf
- modules/cluster/local.tf
> fix: use data source to find oidc url for existing clusters

- versions.tf
Support for tf 0.14
fixes #218
> feat: support tf 0.14

- README.md
- examples/jx3/outputs.tf
- modules/cluster/irsa.tf
- modules/cluster/local.tf
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- outputs.tf
- test/terraform_eks_test.go
- variables.tf
> feat: create iam role for pipeline visualizer

- modules/cluster/irsa.tf
- modules/cluster/main.tf
> fix: update vpc and irsa module to support tf 0.14

- .gitignore
- Makefile
- examples/existing-cluster/main.tf
- modules/cluster/main.tf
- modules/health/main.tf
- modules/vault/local.tf
- modules/vault/main.tf
- versions.tf
> fix: move versions from provider blocks

- jenkins-x.yml
- scripts/ci.sh
- scripts/lint.sh
- scripts/security.sh
> fix: use upstream terraform image

- README.md
- examples/existing-cluster/main.tf
- jenkins-x.yml
- modules/cluster/irsa.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- modules/health/main.tf
- modules/vault/local.tf
- modules/vault/main.tf
- variables.tf
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
Creates bucketrepo roles and policies.
fixes https://github.com/jenkins-x/bucketrepo/issues/50, fixes https://github.com/jenkins-x/bucketrepo/issues/51
> feat: bucketrepo irsa

- templates/jx-requirements.yml.tpl
> fix: remove unnecessary environments

- examples/existing-cluster/main.tf
- modules/cluster/irsa.tf
- modules/cluster/main.tf
- modules/vault/main.tf
> fix: remove hardcoded aws partition in arn

- modules/backup/main.tf
- modules/cluster/main.tf
- modules/cluster/storage.tf
- modules/vault/main.tf
> fix: make clustername lowercase so that s3 bucket names are valid

- examples/jx3/outputs.tf
- modules/cluster/main.tf
- versions.tf
> chore: add support for tf 0.15

- README.md
- examples/jx3/main.tf
- examples/jx3/nginx_values.yaml
- examples/jx3/variables.tf
- main.tf
- modules/nginx/main.tf
- modules/nginx/nginx_values.yaml
- modules/nginx/variables.tf
- variables.tf
> feat: create nginx resources in terraform

- main.tf
- modules/cluster/irsa.tf
> fix: set empty policy arn if create tekton role is set to false

- modules/cluster/irsa.tf
- modules/cluster/local.tf
> fix: added missing comma

- modules/cluster/outputs.tf
- outputs.tf
To be able to do further configuration on the eks cluster the module needs to be outputted. In my case I need to configure scheduling and security groups.
> feat: Output eks module

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Support creating cluster in existing VPC
> feat: Create cluster in existing VPC

- modules/cluster/outputs.tf
I made a typo when cleaning up #272, which broke it. This fixes that.
> fix: Output eks module to get access to it's outputs

- README.md
- examples/jx3/outputs.tf
- modules/cluster/local.tf
- modules/cluster/main.tf
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- outputs.tf
- variables.tf
> chore: output vpc id

- versions.tf
> chore: support tf 1.X.Y

- modules/cluster/charts.tf
> fix: upgrade git operator

- README.md
> Fixes wrong link to Secrets Management

- README.md
- examples/jx3/main.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> fix: make local exec interpreter configurable to support windows

- .github/workflows/release.yml
> ci: migrate docker image from gcr to ghcr

- README.md
The sample values file for using cluster-autoscaler is not using correct keys for the latest versions.
fixes #
> docs: updated sample values file for cluster-autoscaler

- modules/vault/charts.tf
> fix(iss): update vault operator chart to 1.14.3

- modules/vault/charts.tf
> fix: jx vault image to latest

- main.tf
- modules/cluster/irsa.tf
> fix: pass bucket creation variables to the cluster module

- .github/workflows/release.yml
- .jx/updatebot.yaml
> ci: update tf module version in jx3 version

- .github/workflows/release.yml
> ci: fix uses attribute

- .github/workflows/release.yml
> ci: use a different token

- modules/vault/main.tf
> fix: set rcu and wcu to null when dynamo mode is set to on-demand

- local.tf
- templates/jx-requirements.yml.tpl
> fix: add conditionals for jx v2 variables in requirements tpl

- modules/backup/main.tf
- modules/cluster/storage.tf
- modules/vault/main.tf
- versions.tf
Upgrade tf provider to 4.0+ and remove all deprecations in the module because of the upgrade.
fixes #339
> feat: upgrade aws tf provider to 4

- modules/cluster/charts.tf
> chore: upgrade jx-git-operator to 0.0.198

- modules/vault/charts.tf
it broke latest version of aws-load-balancer-controller
> fix: stop creating bogus ingress

- modules/cluster/charts.tf
Update version of jx-git-operator to the last version published 0.0.198 -> 0.1.7
fixes #
> Upgrade-jx-git-operator

- README.md
> fix: markdown formatting

- README.md
> fix: removing unrelated doc

- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/cluster/storage.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
We have created extra var to add more tags in S3 buckets
> chore: add s3 extra tags

- modules/cluster/irsa.tf
Syncing with https://github.com/kubernetes/autoscaler/blame/master/cluster-autoscaler/cloudprovider/aws/README.md
> chore: update cluster autoscaler permissions

- .github/pull_request_template.md
> fix: update pull_request_template.md

- modules/vault/charts.tf
replace broken helm repository for bank-vaults
Also upgrade bank-vault and vault
part of fix for jenkins-x/jx#8688
> fix: replace broken helm repository, upgrade bank-vaults and vault

- README.md
- main.tf
- modules/backup/README.md
- modules/cluster/README.md
- modules/vault/README.md
- modules/vault/charts.tf
- modules/vault/variables.tf
- variables.tf
> feat: support providing values to vault charts

- templates/jx-requirements.yml.tpl
> fix: remove empty vault key

- modules/cluster/irsa.tf
- modules/cluster/storage.tf
> fix: remove unnecessary permissions for buildcontroller
