- modules/cluster/irsa.tf
This PR fixes missing ECR access policy permission that breaks build pipeline with the error:
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/igdianov/test-springboot-app:0.0.1": unsupported status code 401; body: Not Authorized
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.
```
fixes #33
> fix(tekton-bot-policy): add missing ecr policy access permission

- README.md
The generated jx-requirments.yml should only be used on initial `jx boot`
fixes #34
> fix: adding note to README about use of jx-requirements.yml

- modules/vault/main.tf
When `vault_user` input parameter is empty, it causes the below error now:
```
Error: Error attaching policy arn:aws:iam::<account>:policy/vault_<region>-<timestamp> to IAM User : InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, AttachUserPolicyInput.UserName.
on modules/vault/main.tf line 173, in resource "aws_iam_user_policy_attachment" "attach_vault_policy_to_user":
173: resource "aws_iam_user_policy_attachment" "attach_vault_policy_to_user" {
```
fixes #46
> fix: use data source to attach vault policy

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Considering that we can save up to 90% and we are developing resilient applications anyway, we need to add an option that allows using spot instances instead.
fixes #75
> feat: adding an option to use spot instances

- README.md
- examples/nodegroup/main.tf
- examples/nodegroup/variables.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Two things:
1. Need to decide on tags to use
2. To provision node groups, we have to set `enable_worker_group` explicitely to false, else both node group and self managed worker group instances are provisioned. I have added a readme warning. Is this ok? I did this to maintain backwards compatibility. By default enable_worker_group is true, and enable_node_group is false. We could set both of them to false, and make the end user explicitely specify what we want them to use. Thoughts?
Fixes #66
> feat: add support for eks managed node group

- modules/vault/main.tf
- modules/vault/variables.tf
The Free Tier for DynamoDB is On-Demand 25 Read Capacity Units and 25 Write Capacity Units. This is used as the default. The old setting is available as an option which is Provisioned with 2 RCU and 2 WCU is set as default.
fixes #86
> feat: using on-demand as default billing for dynamodb

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
For security purposes, the worker nodes should be on a private subnet by default. 
The example EKS module places the workers on the private subnet.
```
module "eks" {
source       = "../.."
cluster_name = local.cluster_name
subnets      = module.vpc.private_subnets
```
Due to lack of private subnet definition it is placed on the defined public subnet.
fixes #88
> feat: using private subnets as default and adding an option to use public subnets

- Makefile
- examples/backend/outputs.tf
- examples/basic/outputs.tf
- examples/nodegroup/outputs.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/outputs.tf
We already had a variable to specify the size of the disks used by the eks node group nodes, but it was never passed to the cluster module. This PR fixes that.
The latest version of tfsec panics, and breaks the checks. This PR pins the version of tfsec to v0.21.0
It's a bit weird that the master branch had code which was not formatted. 
fixes #105
> fix: allow enduser to specify node group disk size

- README.md
- examples/dev-team/main.tf
- examples/dev-team/outputs.tf
- examples/dev-team/user-alice.tf
- examples/dev-team/user-bob.tf
- examples/dev-team/user-group-developers.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Adds ability to set aws_auth mapper variables - `map_users`, `map_accounts`, and `map_roles`
Example:
```
resource "aws_iam_user" "patrick" {
name = "patrick"
}
module "eks-jx" {
source  = "jenkins-x/eks-jx/aws"
map_users = [
{
userarn  = aws_iam_user.patrick.arn
username = aws_iam_user.patrick.name
groups   = ["system:masters"]
}
]
}
```
Here is a terraform plan, just with ARN's edited and replaced with "XXX"
```
> terraform plan
~ resource "kubernetes_config_map" "aws_auth" {
binary_data = {}
~ data        = {
"mapAccounts" = jsonencode([])
"mapRoles"    = <<~EOT
- "groups":
- "system:bootstrappers"
- "system:nodes"
"rolearn": "arn:aws:iam::XXX:role/project-eks-XXX"
"username": "system:node:{{EC2PrivateDNSName}}"
EOT
~ "mapUsers"    = <<~EOT
- - userarn: arn:aws:iam::XXX:user/patrick
- …
```
> feat: expose eks module's aws_auth mappers

- README.md
- examples/nat/main.tf
- examples/nat/outputs.tf
- examples/nat/variables.tf
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Signed-off-by: Yuki Nagai <ynagai@r.recruit.co.jp>
We would like to use nat gateways for private subnets.
```terraform
private_subnet_tags = {
"kubernetes.io/cluster/${var.cluster_name}" = "shared"
"kubernetes.io/role/internal-elb"           = "1"
}
```
This block is additional.
I referred [here](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html) and [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7de18cd9cd882f6ad105ca375b13729537df9e68/examples/managed_node_groups/main.tf#L72-L75).
If the block should be remove in this PR, please let me know.
fixes https://github.com/jenkins-x/terraform-aws-eks-jx/issues/113
> feat: nat gateway

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
There is a need to have the ability to be able to specify SSH Key Pair Name, EBS Volume Size and Type to the Auto Launch Configuration
fixes #83
fixes #84
> feat: add an option to be able to specify ssh key pair name, ebs volume size and type to the auto launch configuration

- README.md
Adds aws-cli as a listed dependency for the module installation. As noted in the issue, the module fails to apply unless the aws-cli is available and configured.
```
module.eks_jx.module.cluster.null_resource.kubeconfig (local-exec): Executing: ["/bin/bash" "-c" "aws eks update-kubeconfig --name tf-jx-helping-wren"]
module.eks_jx.module.cluster.null_resource.kubeconfig (local-exec): /bin/bash: aws: command not found
Error: Error running command 'aws eks update-kubeconfig --name tf-jx-helping-wren': exit status 127. Output: /bin/bash: aws: command not found
```
Opened here as a recommendation from the [original issue in the jx repo](https://github.com/jenkins-x/jx/issues/7532) 
fixes #134
> docs: Add aws-cli as prerequisite

- README.md
- outputs.tf
Allows user to reuse cluster oidc issuer url
For example in setting up knative with auto tls injection.
> feat: expose cluster oidc issuer url - fixes #150

- README.md
- modules/cluster/irsa.tf
- modules/cluster/outputs.tf
- outputs.tf
This does not automatically install cluster-autoscaler, it installs all of the prerequisite policies and roles required to install autoscaler. The actual autoscaler installation varies depending on what version of kubernetes you are using.
This is probably possible to automate with the helm provider and some refactoring, but that can be a separate endeavor.
To install cluster autoscaler see README.md
fixes #135
> feat: cluster autoscaler - fixes #135

- modules/cluster/irsa.tf
- modules/cluster/local.tf
This PR adds jx3-conditional changes to the IAM role names for the cert-manager and external-dns IAM roles. It removes the random generated seed so the names are predictable and usable in subsequent version stream'ed charts (i.e. role ARN annotations).
You'll notice that the cert-manager IAM role has a "weird" name of `<CLUSTER NAME>-cert-manager-cert-manager`.
This is because the convention across the board seems to be that the IAM roles are named according to `<CLUSTER NAME>-<NAMESPACE OF THE SA IT SERVES>-<NAME OF THE SA>`. I've kept this, as it also matches up nicely with the role-arn annotations in the version stream for the cert-manager and external-dns chart templates. We can change this but we'll just need to update those templates in the version stream simultaneously.
fixes #175 …
> fix: update iam roles to jx3 naming scheme and match sa names to trust relationships

- modules/cluster/local.tf
Just edit the old Terraform variable style that was deprecated at the submodule cluster.
remove the `"${ sequence from the start and the }"`
Warning: Interpolation-only expressions are deprecated
fixes: #190
> fix: fixed deprecate

- README.md
- examples/asm/main.tf
- examples/asm/outputs.tf
- examples/asm/variables.tf
- local.tf
- main.tf
- modules/vault/local.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- templates/jx-requirements.yml.tpl
- variables.tf
The `use_asm` does not add any support for AWS Secrets Manager yet, just sets the `secretStorage` value to `asm` instead of vault in the `jx-requirements` template.
fixes #183
> feat: disable vault resource creation if vault is not used

- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- variables.tf
Allow for custom velero usernames to be passed as a variable to the module. This allows for multiple velero instances under the same AWS account, whereas previously it would cause an IAM username conflict.
Variable is optional and default will result in same outcome as currently expected - username of 'velero'.
None
fixes #209
> feat: custom velero username

- modules/cluster/irsa.tf
fix: add object access to visualizer policy
Give not only bucket access but also object access to the visualizer, or it will get no access to the logs:
status code: 403, request id: 6301D24E45EF1903, host id: Lqtrx39JLM289tl7UODgB2z3V53nGuxv7kLVNQse8qw7ZqmBfh/JIogNBcWGOuAyaj4dE83Fwpk=
fixes #
> fix: add object access to visualizer policy

- versions.tf
On clean install, without adding the following to main.tf, it fails to create the cluster.
```
provider "helm" {
version = "1.3.2"
}
```
It gives the following error:
```
module.eks-jx.module.cluster.helm_release.jx-git-operator[0]: Creating...
Error: provider not configured: you must configure a path to your kubeconfig
or explicitly supply credentials via the provider block or environment variables.
See our authentication documentation at: https://registry.terraform.io/providers/hashicorp/helm/latest/docs#authentication
```
After adding it to main.tf, it warns that adding provider in main.tf is deprecated, and it should be added to required providers instead, so here is the pull request.
fixes #
> fix: Adding helm

- main.tf
The `create_<app>_role` are not really passed to the cluster submodule, so the roles are always created regardless of what the user sets in these parameters. This PR tries tof fix this.
> fix: pass through the create_<app>_role variables

- README.md
- main.tf
- modules/cluster/irsa.tf
- modules/cluster/variables.tf
- variables.tf
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
Allows user to provide additional policy ARNs
For example, for `serverless deploy` permissions:
```
data "aws_iam_policy_document" "tekton-bot-policy-serverless" {
statement {
sid    = "tektonBotPolicyServerless"
effect = "Allow"
actions = [
"cloudformation:*",
"s3:*",
"logs:*",
"iam:*",
"apigateway:*",
"lambda:*",
"ec2:DescribeSecurityGroups",
"ec2:DescribeSubnets",
"ec2:DescribeVpcs",
"events:*",
"sqs:*"
]
resources = ["*"]
}
}
resource "aws_iam_policy" "tekton-bot-serverless" {
name_prefix = "jenkins-x-tekton-bot-serverless"
description = "tekton-bot serverless deploy policy"
policy      = data.aws_iam_policy_document.tekton-bot-policy-serverless.json
}
module "eks-0-jx" {
source  = "jenkins-x/eks-jx/aws"
version = "1.15.3" …
```
> feat: allow additional policies to be passed to tekton IRSA role

- modules/cluster/irsa.tf
Currently, if the creation of IAM roles is disabled by setting the right input variables to false, the apply fails as the assumable role module inputs use output from IAM policies that aren't being created. This makes the use of these ARNs conditional on them being created.
> fix: conditionally add role_policy_arns

- modules/vault/main.tf
Such as described in https://github.com/hashicorp/terraform/issues/5617
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
The tf module currently flip flops every plan and apply due to the dynamodb capacities changing. 
After:
```
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Releasing state lock. This may take a few moments...
```
> fix: prevent flip-flopping state by ignoring dynamodb capacity changes

- README.md
- main.tf
- modules/cluster/local.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
This PR allows for compliant use of EKS node groups with the [terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/node_groups) which results in instance settings being enforced.
Further, the changes also allow for overriding the default node group to allow for multiple node groups and the use of launch templates.
Introduces new input, 'node_groups_managed', for setting custom node groups.
fixes #248
> EKS node groups overhaul

- main.tf
Remove provider block from main.tf. This provider prohibits passing down a provider configuration from a parent terraform project, which makes it difficult to make this module work in multi-account environments where multiple providers are defined and used to assume various roles within the AWS org.
It is also recommended by the terraform documentation that a module intended to be used by other modules should not include provider configurations:
https://www.terraform.io/docs/language/modules/develop/providers.html
> fix: remove provider block

- README.md
- examples/jx3/variables.tf
- modules/cluster/main.tf
- variables.tf
* Remove cluster version default, let users decide which version they want, else its magic and people may create old eks clusters
* Pass the endpoint cidr variables
fixes #
> fix: remove default for cluster version

- README.md
- main.tf
- modules/cluster/irsa.tf
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- outputs.tf
- variables.tf
This commit will create a ServiceAccount to access SSM and Secrets
Manager.
The resources this ServiceAccount has access to are for the ones JX
defines in it's secretMapping
Allows all Read/Write Secrets in both SSM Parameter Store and Secrets Manager for the resources defined in the secretMappings added in [this PR](https://github.com/jenkins-x/jx3-versions/pull/2544)
> feat: create service account for secrets

- modules/nginx/main.tf
This is a fix to get rid of the warning:
```
Warning: Interpolation-only expressions are deprecated
on .terraform/modules/eks-jx/modules/nginx/main.tf line 10, in resource "helm_release" "nginx-ingress":
10:     fileexists("${path.cwd}/${var.nginx_values_file}") ? "${file("${path.cwd}/${var.nginx_values_file}")}" : "${file("${path.module}/${var.nginx_values_file}")}"
```
> fix: Get rid of interpolation warning

- modules/vault/main.tf
Without this fix creation of aws_kms_key fails with:
MalformedPolicyDocumentException: The new key policy will not allow you to update the key policy in the future.
> fix: Allow applying terraform with non root IAM user

- modules/cluster/local.tf
- modules/cluster/variables.tf
- variables.tf
Allow leaving out default values and adding more fields to node groups. 
After #252 was applied you could specify attributes for node groups, but the way it was implemented you had to specify all fields even if you where content with the defaults and you also could not add more attributes (in my case subnets and name).
This PR fixes that.
> Allow leaving out default values and adding more fields to node groups

- main.tf
vault defaults to us-east-1, instead of the region used by the rest of the stack
fixes #
> fix: added region to vault

- main.tf
- modules/dns/main.tf
- modules/dns/variables.tf
- variables.tf
When doing terraform destroy and you have set create_and_configure_subdomain then it will fail with HostedZoneNotEmpty if there are entries in the zone (typically created by external-dns). This fix gives to option to have the zone destroyed anyway.
> fix: Prevent HostedZoneNotEmpty during terraform destroy

- modules/cluster/irsa.tf
- modules/cluster/outputs.tf
renamed parameter-store to secret-manager as ExternalSecrets uses that
convention.
related: https://github.com/jenkins-x/jx3-versions/pull/2619
> fix: use external-secret standard naming

- modules/cluster/irsa.tf
- templates/jx-requirements.yml.tpl
Terraform sets the name of the secretStorage to "asm", which is not recognised in the gitops operator, who expects the name "secretsManager". The current setup makes the default configuration the only configuration you ever can get. Which makes it really hard to change things.
> fix: change secrets manager name in requirements file

- modules/vault/charts.tf
This should fix that secrets failed to be populated from vault by kubernetes-external-secrets. The log of kubernetes-external-secrets showed errors like:
{"level":50,"time":1630943166224,"pid":17,"hostname":"kubernetes-external-secrets-7686994b8c-ldrwh","payload":{"response":{"statusCode":400,"body":{"errors":["invalid role name \"jx-vault\""]}}},"msg":"failure while polling the secret jx/lighthouse-hmac-token"}
fixes #
> fix: External secrets from vault

- examples/customers_certificate/main.tf
- modules/cluster/irsa.tf
- modules/cluster/local.tf
- modules/dns/main.tf
External secrets does not work with IRSA because the pod cannot assume the iam role attached to the service account.
The reason is that in the  the assume role policy document the namespace of the external secrets service account is set to jx namespace, but the it's in secret-infra account
fixes #293
> fix: change external secrets namespace to secret-infra

- modules/cluster/charts.tf
this leads to additional breakages, as the older chart version may point to a docker image that no longer exists: https://kubernetes.slack.com/archives/C9LTHT2BB/p1631639873074600
Signed-off-by: Patrick Lee Scott <pat@patscott.io>
fixes #
> fix: lifecycle ignore prevents users from chart version updates

- main.tf
- modules/cluster/charts.tf
- modules/cluster/variables.tf
- variables.tf
Make it possible to add helm value to the jx-git-operator helm chart
fixes #303
> Git operator values

- CONTRIBUTING.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Many companies use the AWS best practice of requiring users to assume into a role that grants access to a given account representing an environment (dev, stage, prod etc). When I tried to spin up a cluster using the [jx3-terraform-eks](https://github.com/jx3-gitops-repositories/jx3-terraform-eks) repo, it failed because in this module, there is a direct call to AWS that doesn't honor the profile I set in the  [jx3-terraform-eks](https://github.com/jx3-gitops-repositories/jx3-terraform-eks) terraform variables. This PR adds a conditional flag on the only direct AWS call I could find. Please point out if there are more.
In theory this should be backwards compatible because if the variable isn't set the flag wouldn't be added. If this is pulled in I will need to make a separate PR in …
> Fix #288: not able to use AWS Profiles

- examples/jx3/main.tf
- main.tf
- modules/cluster/charts.tf
- modules/cluster/variables.tf
- variables.tf
This PR adds a `boot_secret` variable which can set some env variables during the boot process to make working with external vault more convenient.
fixes #324
> feat: add variable to set boot secrets

- .github/pull_request_template.md
- main.tf
Fixes a bug where custom ASM role was always set as blank even if the user set the correct value in asm_role variable.
> fix: pass custom asm_role to the cluster submodule

- OWNERS
- modules/cluster/irsa.tf
When giving the variable `enable_repository_storage = false` to the module I got this error:
```
│ Error: Invalid index
│
│   on .terraform/modules/eks-jx/modules/cluster/irsa.tf line 361, in data "aws_iam_policy_document" "bucketrepo-policy":
│  361:     resources = [aws_s3_bucket.repository_jenkins_x.*.arn[0], "${aws_s3_bucket.repository_jenkins_x.*.arn[0]}/*"]
│     ├────────────────
│     │ aws_s3_bucket.repository_jenkins_x is empty tuple
│
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/eks-jx/modules/cluster/irsa.tf line 361, in data "aws_iam_policy_document" "bucketrepo-policy":
│  361:     resources = [aws_s3_bucket.repository_jenkins_x.*.arn[0], …
```
> fix: Check existence of correct bucket for bucketrepo

- README.md
- modules/health/variables.tf
- variables.tf
Kuberhealthy is anyways not working since 1.22 and causes lot of issues for new users.
Disabling it by default makes sense IMO.
Also it's not core jx.
fixes #
> feat: disable kuberhealthy installation by default

- README.md
- main.tf
- modules/cluster/local.tf
- modules/cluster/variables.tf
- variables.tf
Unless you set use_asm it was previously not possible to set boot_iam_role.
You couldn't add it with 
boot_secrets                    = [
{
name  = "bootServiceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
value = "arn:aws:iam::${var.aws_account}:role/jx-boot-job"
type  = "string"
}
]
either, since it would be overwritten with an empty value,
Since the role can be used for other things than asm I added a new input to make that clear.
> feat: Allow specifying boot_iam_role

- modules/cluster/irsa.tf
The cluster autoscaler has new functionality for eks in 1.24 that requires more permissions.
- [Documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#iam-policy)
- [The commit](https://github.com/kubernetes/autoscaler/commit/b4cadfb4e25b6660c41dbe2b73e66e9a2f3a2cc9)
> fix: add permissions needed for cluster autoscaler 1.24

- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/cluster/storage.tf
- modules/cluster/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- variables.tf
Starting in April 2023, Amazon S3 will introduce two new default bucket security settings by automatically enabling S3 Block Public Access and disabling S3 access control lists (ACLs) for all new S3 buckets. Once complete, these defaults will apply to all new buckets regardless of how they are created, including AWS CLI, APIs, SDKs, and AWS CloudFormation.
This AWS change results in the error **AccessControlListNotSupported: The bucket does not allow ACLs** when  creating a new EKS environment.
This change replaces the use of **_aws_s3_bucket_acl_** resource with the **_aws_s3_bucket_ownership_** resource. The rule for the ownership is **_BucketOwnerEnforced_**.
In the event ACL is still the preferred bucket permission type, you can set a new variable `enable_acl=true.` 
The tests were …
> S3 Block Public Access Fix

- versions.tf
Remove 'template' from the list of required providers.
- None of the resources/datasources provided by this provider are currently in use.
- It has been deprecated since terraform 0.12 and no longer in development, e.g. there is no official build for darwin_arm64.
> remove template provider

- README.md
- main.tf
- modules/cluster/charts.tf
- modules/cluster/irsa.tf
- modules/cluster/main.tf
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- outputs.tf
- test/terraform_eks_test.go
- variables.tf
Building/upgrading AWS to  v1.23 and greater versions now require a container storage interface (CSI) driver. 
[The Kubernetes in-tree to container storage interface (CSI) volume migration feature was enabled in K8S version 1.23.](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) This feature enables the replacement of existing Kubernetes in-tree storage plugins for Amazon EBS with a corresponding Amazon EBS CSI driver. 
An add-on is software that provides supporting operational capabilities to Kubernetes applications, but is not specific to the application.  [EKS Addons Guide ](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) 
This fix introduces Terraform resources to build and manage the Amazon EKS Add-on for the Amazon Elastic Block Store …
> fix: ebs csi driver addon (jx#8575)

- README.md
- modules/cluster/outputs.tf
- outputs.tf
The latest release for the eks-jx module 1.21.8  does not include output variables for the new addon irsa role. This request provides the variables and updates to the README.md on how to enable EBS CSI driver addon.
The following output variable should also be added to [https://github.com/jx3-gitops-repositories/jx3-terraform-eks/output.tf](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/blob/main/output.tf)
```
output "ebscsi_addon_iam_role" {
value       = module.eks-jx.ebscsi_addon_iam_role
description = "The IAM Role that the build pods will assume to authenticate"
}
```
> feat: ebs csi driver addon output

- modules/backup/main.tf
- modules/cluster/storage.tf
As a best practice to save costs there should be a lifecycle configuration on s3 buckets to abort incomplete uploads
https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-abort-incomplete-mpu-lifecycle-config.html
> fix: abort incomplete uploads to s3 bucket

- modules/backup/main.tf
- modules/cluster/storage.tf
As a best practice to save costs there should be a lifecycle configuration on s3 buckets to abort incomplete uploads
https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-abort-incomplete-mpu-lifecycle-config.html
fixes #
> fix: abort incomplete uploads to s3 bucket (#379)

- README.md
- variables.tf
It's confusing and annoying that nginx_chart_version is required even if you set `create_nginx = false`. Also if you nginx_chart_version is null while `create_nginx = true` is fine; it just means you get the latest version.
> fix: don't require nginx_chart_version to be set
